### ISSUE TITLE
[W3-pipelines-project] Olaya Marqués Gómez

### ISSUE THREAD

**Issue by olaya-marques** [Ironhack-Data-Madrid-Mayo-2021/W3-pipelines-project#1]
Este es el link que lleva a mi trabajo: https://github.com/olaya-marques/w3-pipelines-project
Muchas gracias!

**Comment by olmocorell** [comment]
¡Hola Olaya!
Vengo a corregir tu proyecto de pipelines donde enriquecíamos datos... allá voy

### Readme
En cuanto a esto... nada que decir, la verdad, es la perfección absoluta, enhorabuena.

### Code/Repository structure
La estructura del repositorio en general está bien, excepto el tema de todos los csv fuera..
![Captura de pantalla 2021-07-06 a las 16 18 26](https://user-images.githubusercontent.com/57899051/124615689-cc983880-de75-11eb-9b8c-84041ba17a4a.png)

No me importa que llames a la carpeta de source "funciones", aunque es más correcto que la gente sepa que ahí hay código fuente del que bebe tu proyecto.... pero lo que sí o sí es más conveniente es tener todos los csv organizados dentro de una carpeta de data ¿valep?
Y sobre todo, no me llames al archivo de funciones "funciones.py" ¿Vale? utilizamos nombres descriptivos para las variables y también 

En cuanto a los jupyter notebook....el trabajo que has hecho comentando todo es espectacular, pero si ya sabemos sacar las funcionoes a un .py e imprtarlas....¡hagámoslo! todas las funciones van fuera del jupyter ¿Vale?

![Captura de pantalla 2021-07-06 a las 16 38 55](https://user-images.githubusercontent.com/57899051/124619126-a9bb5380-de78-11eb-91ef-06b8bc69a9aa.png)

Dentro de las funciones, felicitarte porque hayas hecho los docstrings de las funciones correctamente.

### Code efficiency / Code syntax (conventions)
El código de los jupyter está bien, haces lo que necesitas para obtener datos de una api y web scraping.
Me ha faltado la parte de automatización, pero me ha encantado ver el proceso y los jupyter comentados.
En cuanto al de visualización, haces todo esto en busca de estudiar un tema y concluyes solamente con una frase... me habría gustado ver más comentarios en la parte del storytelling.

### Improvements
- Funciones fuera del jupyter
- Automatización de procesos (funciones que luego son llamadas en un pipeline)
- Más explicación en storytellin

En general, has hecho un trabajazo, solo el hecho de que hayas hecho tanto api como web scraping dice mucho, así que... ¡¡ENHORABUENA!!


![project](https://user-images.githubusercontent.com/57899051/124620810-0c611f00-de7a-11eb-9cab-dc5b658e354b.png)
