### ISSUE TITLE
[W3-pipeline-project] Cristian Castro Blua

### ISSUE THREAD

**Issue by ccastroblua** [Ironhack-Data-Madrid-Mayo-2021/W3-pipelines-project#2]
https://github.com/ccastroblua/nba-potm-project.git

**Comment by sheriffff** [comment]
Buenísimo readme. En la última parte, puedes poner los links más guays de esta forma `[Pandas](https://pandas.pydata.org/)` y no se muestra el link pero "Pandas" es clikable ;)

Muy claro el cleaning.ipynb:
 - Bien comentado
 - Buen uso de los `apply`, me alegro que le hayas pillado el truco. Es poco eficiente pero a veces muy útil.
 - Bien usado `.to_csv(index=False)` para no guardar el file con morralla
 
Bien el scrapping.ipynb
 - Cuando chequees el valor de un objeto, por ejemplo en la celda `In [6]`, quizás es bueno poner `pom_dataset[:10]` para ver sólo una muestra, pues en Github queda output gigante sino.

Guay el analysis.ipynb
 - Me gusta mucho la creación del ratio de 3-point y field goals. Somos DS y tenemos que inventarnos Features buenas como esa!
 - Buena conclusión en cuanto a puntos rebotes y asistencias. Queremos conclusiones claras y sencillas como esas.
 - Buen uso de histogramas y boxplots, me alegro que les veas la utilidad.

Well done!
