### ISSUE TITLE
[W3-pipelines-project] - Alvaro Garcia Blazquez

### ISSUE THREAD

**Issue by alvarogb1919** [Ironhack-Data-Madrid-Mayo-2021/W3-pipelines-project#3]
Buenas! El link a mi repo es: https://github.com/alvarogb1919/Unicorn-companies-analysis

**Comment by sheriffff** [comment]
Buen README. En el Scope of the project, asegúrate que los bullet points 1) 2) 3) etc quedan en líneas separadas. Basta con poner doble espacio al final de la línea, que el markdown entenderá que es una nueva línea. No le vale con un Enter.
Además, en las librerías, utiliza la sintaxis `[Pandas](https://pandas.pydata.org/)`, que no muestra el link feo y crea un link en "Pandas" ;)

Muy bien que tengas un archivo de funciones para llamar, nos vamos acostumbrando a esto. Aunque te haya dado algún problema en `Unicorns cleaning_called_functions.ipynb`, debemos tener esta filosofía de modularización.

Buen notebook `clean.ipynb`:
 - Buen uso del apply. Llamas a funciones de fuera. Es preferible que los import no estén dentro de cada función, si no al principio del archivo `.py`.
 - Buen uso de `value_counts`, de mis funciones preferidas para hacernos idea del dataset.
 - Cuando haces `response_1.content` en la celda 76, puedes hacer mejor `response_1.content[:100]` para ver sólo los primeros caracteres. Si no al ver el notebook en Github es giganteeeesco el output y molesto. Yo a veces tampoco me acuerdo, pero bear it in mind.
 - Buena investiación para traerse el contenido a veces con `html.parser`. Cosas del scraping...

Buen análisis!!
 - a1, a2. Top countplot en horizontal y no en vertical. La paleta me parece apropiada. Se agradece la conclusión escrita al final. Te animo a poner bullet points más que el troncho de 6 líneas.
 - a3. Guay el histograma por año. Se ve clara tendencia. 
 - a4. Gran scatterplot con valuaciones por año. Cuando muchos puntos se acumulan en una zona y no sabemos si hay muchos o pocos, podemos usar el parámetro `alpha=0.3` para dar transparencia a los puntos. Toma nota!
 - Echo de menos en el notebook algun scatter con hue para dar color según categoría. Aunque quizás queda un poco cargado, lo probaría.

Echo de menos un archivo `.py`. Es verdad que en clase trabajamos mainly con notebooks, pero está bien que aprendamos a dejar un proceso, por ejemplo el de cleaning, en un `.py`. De manera que al hacer desde terminal `python clean.py` se haga todo el proceso que lee csv, lo limpia y crea otro csv limpito.

Felicidades por el gran proyecto Álvaro!
