### ISSUE TITLE
[W3-pipelines-project] - Santi  Moreno Pidal

### ISSUE THREAD

**Issue by Santimo89** [Ironhack-Data-Madrid-Mayo-2021/W3-pipelines-project#5]
https://github.com/Santimo89/W3-pipelines-project

**Comment by olmocorell** [comment]
¡Hola Santi!
Como ya hemos hablado esta mañana, tu proyecto está a medias, pero no desfallezcas, es importante que sigas trabajando y esforzándote por llegar a entender y dominar poco a poco todas las tecnologías que vayamos viendo durante el bootcamp.
En cuanto a las apis, mi recomendación...busca y elige una, peléate con ella, trata de entenderla y de obtener información, y así, otra, y poco a poco, verás que cada API es un mundo pero que pueden ser y son realmente útiles.
Espero que el próximo proyecto se te dé mejor y en el futuro encuentres un hueco para mejorar este y sacarle partido.
Cualquier cosa que necesites cuenta conmigo.
Ánimo Ironhack es una carrera de fondo y lo importante es llegar vivo.

![image](https://user-images.githubusercontent.com/57899051/122956055-f71bc900-d380-11eb-889b-8e62effb1a56.png)
