### ISSUE TITLE
[W3-pipelines-project] Victoria Ruiz 

### ISSUE THREAD

**Issue by Vicrgallardon** [Ironhack-Data-Madrid-Mayo-2021/W3-pipelines-project#6]
https://github.com/Vicrgallardon/Data-Pipeline.git

**Comment by olmocorell** [comment]
¡¡Hola Vicky!!
Vamos a ver qué tal está tu proyecto...

### Readme
¿Qué pasó?
![Captura de pantalla 2021-07-06 a las 16 51 27](https://user-images.githubusercontent.com/57899051/124621255-695cd500-de7a-11eb-8fbd-c94edcc06139.png)
Te diré que antes había una norma y es que un proyecto sin readme no se corregía....y contabilizaba como no entregado.
Voy a corregírtelo y a darte feedback pero... esto es realmente malo de cara a tu portfolio ¿vale? 
Los proyectos que realizamos son para, además de practicar lo aprendido, nutrir de contenido vuestro github, que de ahora en adelante será vuestro portfolio así que... ¡cuidemos eso

### Code/Repository structure
En cuanto a estructura del código:
![Captura de pantalla 2021-07-06 a las 16 53 06](https://user-images.githubusercontent.com/57899051/124621526-a3c67200-de7a-11eb-918e-336b3143eae9.png)
Ese DS_Store lo metemos en el gitignore ¿vale?
Por otra parte, ese csv lo metemos en una carpeta de data... 

En cuanto a modularización del código y archivos de funciones.... utils.py es lo mismo que funciones.py utilizamos nombres descriptivos para las variables y también para los archivos de funciones ¿vale?


### Code efficiency / Code syntax (conventions)
![Captura de pantalla 2021-07-06 a las 17 07 49](https://user-images.githubusercontent.com/57899051/124623918-b346ba80-de7c-11eb-9a8e-9c36a2e3ecd0.png)
En vez de comentar por encima lo que hace una función, lo ideal es hacer docstrings.  Te dejo [este](https://dev.to/highflyer910/what-is-a-python-docstring-44eo) interesante artículo para que le eches un ojo.
![Imagendocstring](https://res.cloudinary.com/practicaldev/image/fetch/s--N0syxVgK--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/265qjt7ekw21lblrokz5.jpg)

Todo ... si repites código hacemos una función ¿vale?
![Captura de pantalla 2021-07-06 a las 17 14 42](https://user-images.githubusercontent.com/57899051/124624953-a9718700-de7d-11eb-89ea-ead35c3530a8.png)



### Improvements
- El proyecto está incompleto.... ya lo sabes
- Falta la parte de enriquecer...
- Modularizar el código
- Falta storytelling
- Dividir los juypter en función de las diferentes temáticas que realizas

Poco te puedo decir, ya sabes lo que te falta porque tú misma me lo dijiste, está sin terminar. No importa si te quedaste atascada con las apis, es importante el resto del trabajo. Espero que el próximo te haya salido mejor. 
Aún así, valoro el trabajo que has realizado, ¡¡sigueeeeeeee!!
¡¡Mucho ánimo!! 

![project](https://user-images.githubusercontent.com/57899051/124625789-66fc7a00-de7e-11eb-935b-5e4b09426bf0.png)
